service: KP1
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
  KP1Consumer:
    handler: functions/consumer.handler
    environment:
      TELEMETRY_TABLE_NAME: !Ref KP1TelemetryTable
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - kinesis:DescribeStream
          - kinesis:DescribeStreamSummary
          - kinesis:GetRecords
          - kinesis:GetShardIterator
          - kinesis:ListShards
          - kinesis:ListStreams
          - kinesis:SubscribeToShard
        Resource: !GetAtt KP1DataStream.Arn
      - Effect: "Allow"
        Action:
          - dynamodb:BatchWriteItem
        Resource: !GetAtt KP1TelemetryTable.Arn
    events:
      - stream:
          type: kinesis
          arn: !GetAtt KP1DataStream.Arn
          parallelizationFactor: 1
          batchSize: 100
          batchWindow: 10
          tumblingWindowInSeconds: 30
          
resources:
  Resources:
    KP1DataStream:
      Type: AWS::Kinesis::Stream
      Properties:
        ShardCount: 3
        StreamModeDetails:
          StreamMode: PROVISIONED
    KP1TelemetryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
  Outputs:
    Output:
      Description: "Kinesis stream name"
      Value: !Ref KP1DataStream
